language: c
script: make
deploy:
  on:
    branch: master
  provider: s3
  bucket: darwins-challenge
  skip_cleanup: true
  local_dir: build
  acl: public_read
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
env:
  global:
    - secure: KAHmXywZUtLKQYkIhYzV2m6RTbmTxogfWssUUrCVeXr1DxFDCqMVLhXt6Q03Uz7Fl+1gqRFa/G83jAWR+jU44r6WTddsjhGcaBvPshCMtLJTbiNqCObkGlj/E8qihqI6t49dJ0he8wLjIQifP+LgSFpeA8yHc1vED7TbYVB6/ysVVXklxjdrjh/g2ICEUSXa/0fvapmTe2zDv/p7oBq8/UV4au2co064lrv5ameG+oneDV2jLd4D5dXqV+CqEmdaXTCzJtokGfY8DJHrCLS5mGTTxRuVDsJOb05ljycpSFijUSuoDm+OIgwL2MHN2qXmCmAicmpaOZctzBCIibpFc4OHtFIGE3xjci0mEPBHk7IzlG7WaGaV8xL38DUGEo4P0u2T9f+vfhrprsNBTU7UHw3vzzI23yQHmyu77LYHcBCO+VfY3L/ir6E62wzgA8NunddhlNKs+AGxFgv/3mIqPx1GyjdF+0EEZpL0s09s9owdKG6yNuJMVXEULRqAaUVJo6LAqwQa6tzuobT5oyI2khP0RtF5r7z2RUkYu9xHFHGDoVFlG/CLPQkDm20CmGJB4IQ1kccPXYFmVT9Js+4ZWSlNdV9Fx+XIO2yTFEycl3bhzdiiFIjUPoSg1Oz+KeHmb1/xynyE9FLhZ15oTVdlx/GvJ1VUj3CyyOsk4o5TOVc=
    - secure: G2K0rMQDLzSj9gsjSE4dwfvKKLkB06jq7OYlQeOezzA7D8zcDfc2+xJrpFGPbOnk2ASxuKfpgTxXx4oph/QTK9AaPcIinN0O9yyGHKn95pjzroPYGHThupB8aI63YsaK9argovXmUaxYKGghAU1LHM7BX4M2C8SBWK/cA6qiK/hvHjFuTTdW47L3zMT3rQ/2h9uC7aTH9iTilxJPwvRpZkRR6n13DW5k/GdplMgdstbWkTfBYoXhXXA2S8w8wznw3QS/a3gwqqvBBaV83+ThLb0W/cVd2cBhBUO9b06s4c7R3cdx0SViLSYTYoJhz9VzhkUvbYq/MKu6Ip0p5bo8u6aj1lJ67+D33uduFlnS+Io0oqRXqG93AQT4FMrtvYjKsytanXeYpz3NTXALBKT93c3c6siT7kkZTLDqalUnScDsXQ0BDnvJbMsO3h94jFhJW05uYfssrCEbxIalnH0zqcy7XRoBlIUop6zZU4A+fQGXkLyUQeahhb8F0ASnNsIfPqBzOjYwTZ6WRI0ANHUBvREEHPostmVMrU0JVdBGX3tD4Q97/QsEcuXGgae5Qc2we7fUjTbPxUHVkNwE+8gzMVY54CRq91wMxZjkNhDSzHzYo90if3i7ncO+kqgliYdygkmj1uy/BkxgdGpaLnWHXVjcJTGeeFin7PKRsqaU818=
